server:
  port: 80

spring:
  application:
    name: test-beatdev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/testbeatdev"
    username: "root"
    password: "db-pass"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  file:
    path: ./
    name: app.log
